/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminControl.java
 *
 * Created on Jan 1, 2011, 10:45:43 AM
 */

package GUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import GUI.Login;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author ThangAPT
 */
public class AdminControl extends javax.swing.JFrame {
//    Color color1 = new Color(239, 159, 36);
//    Color color2 = new Color(133, 172, 229);
//    Color color3 = new Color(100, 143, 229);
    Color color1 = new Color(240, 240, 240);
    Color color2 = new Color(255, 255, 255);
    Color color3 = new Color(133, 172, 229);
    String id = "";
    /** Creates new form AdminControl */
    public AdminControl(String nameUser, String id) {
        initComponents();
        this.id = id;      
        this.setVisible(true);
        setDimension();
        jLabelHome.setIcon(new ImageIcon("src/images/Ico/home.png"));
        jLabelHelp.setIcon(new ImageIcon("src/images/Ico/help.png"));
        jLabelExit.setIcon(new ImageIcon("src/images/Ico/exit.png"));
        //jPanel2.add(new ImagePanel(new ImageIcon("src/images/Ico/bgtop.jpg").getImage(),CENTER_ALIGNMENT));
        //jPanel1.add(new ImagePanel(new ImageIcon("src/images/Ico/bg.png").getImage(),CENTER_ALIGNMENT));
        //jPanel6.add(new ImagePanel(new ImageIcon("src/images/Ico/bgleft.jpg").getImage(),CENTER_ALIGNMENT));
        String[] arrUser = nameUser.split(" ");
        jLabelUserName.setText("Hi, "+arrUser[arrUser.length-1]);
        SetForButton();
        this.setResizable(false);
        this.setTitle("Admin Control");
        setPanelLayout(jPanelcontent, new Manage_City());        
    }
    void SetForButton(){
        btn_ViewInfomation_City.setText("<html><font size =3 color ='black'><b>City</b></font></html>");
        btn_ViewInfomation_District.setText("<html><font size =3 color ='black'><b>District</b></font></html>");
        btn_ViewInfomation_Supermarket.setText("<html><font size =3 color ='black'><b>Supermarket</b></font></html>");
        jPanel3.setBackground(new Color(240, 240, 240));
        jPanel1.setBackground(new Color(240, 240, 240));
        jPanel2.setBackground(new Color(240, 240, 240));
        jPanel6.setBackground(new Color(240, 240, 240));
        jPanelcontent.setBackground(new Color(240, 240, 240));
        btn_ViewInfomation_District.setFocusPainted(false);
        btn_ViewInfomation_City.setFocusPainted(false);
        btn_ViewInfomation_Supermarket.setFocusPainted(false);
        btn_ViewInfomation_District.setBackground(color2);
        btn_ViewInfomation_City.setBackground(color2);
        btn_ViewInfomation_Supermarket.setBackground(color2);
    }
    void setDimension(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension window = new Dimension(getPreferredSize());
        int w = window.getSize().width;
        int h = window.getSize().height;
        int x = (dim.width - w)/2;
        int y = (dim.height - h)/2;
        setLocation(x, y);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabelHelp = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_Left = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btn_ViewInfomation_City = new javax.swing.JButton();
        btn_ViewInfomation_District = new javax.swing.JButton();
        btn_ViewInfomation_Supermarket = new javax.swing.JButton();
        jPanel_Content = new javax.swing.JPanel();
        jPanelcontent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 55));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Guide");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 30, 40, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Logout");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(900, 30, 60, 20);

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUserName.setText("Hi, Admin");
        jLabelUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserNameMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelUserName);
        jLabelUserName.setBounds(900, 10, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Home");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 30, 40, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText(" Exit");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 30, 40, 20);

        jLabelHome.setText("jLabel1");
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelHome);
        jLabelHome.setBounds(10, 0, 34, 30);

        jLabelHelp.setText("jLabel1");
        jLabelHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHelpMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelHelp);
        jLabelHelp.setBounds(60, 0, 34, 30);

        jLabelExit.setText("jLabel1");
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelExit);
        jLabelExit.setBounds(110, 0, 34, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_Left.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ViewInfomation_City.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ViewInfomation_City.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ViewInfomation_CityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ViewInfomation_CityMouseExited(evt);
            }
        });
        btn_ViewInfomation_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewInfomation_CityActionPerformed(evt);
            }
        });

        btn_ViewInfomation_District.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ViewInfomation_District.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ViewInfomation_DistrictMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ViewInfomation_DistrictMouseExited(evt);
            }
        });
        btn_ViewInfomation_District.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewInfomation_DistrictActionPerformed(evt);
            }
        });

        btn_ViewInfomation_Supermarket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ViewInfomation_Supermarket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ViewInfomation_SupermarketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ViewInfomation_SupermarketMouseExited(evt);
            }
        });
        btn_ViewInfomation_Supermarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewInfomation_SupermarketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ViewInfomation_City, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btn_ViewInfomation_District, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btn_ViewInfomation_Supermarket, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ViewInfomation_City, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ViewInfomation_District, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ViewInfomation_Supermarket, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_LeftLayout = new javax.swing.GroupLayout(jPanel_Left);
        jPanel_Left.setLayout(jPanel_LeftLayout);
        jPanel_LeftLayout.setHorizontalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_LeftLayout.setVerticalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelcontent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelcontent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelcontent.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanelcontent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel_ContentLayout = new javax.swing.GroupLayout(jPanel_Content);
        jPanel_Content.setLayout(jPanel_ContentLayout);
        jPanel_ContentLayout.setHorizontalGroup(
            jPanel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelcontent, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        jPanel_ContentLayout.setVerticalGroup(
            jPanel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelcontent, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Left, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Content, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ViewInfomation_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_CityActionPerformed
        setPanelLayout(jPanelcontent, new Manage_City());
        btn_ViewInfomation_District.setBackground(color2);
        btn_ViewInfomation_City.setBackground(color1);
        btn_ViewInfomation_Supermarket.setBackground(color2);

}//GEN-LAST:event_btn_ViewInfomation_CityActionPerformed

    private void btn_ViewInfomation_DistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_DistrictActionPerformed
        setPanelLayout(jPanelcontent, new Manage_District());
        btn_ViewInfomation_District.setBackground(color1);
        btn_ViewInfomation_City.setBackground(color2);
        btn_ViewInfomation_Supermarket.setBackground(color2);
    }//GEN-LAST:event_btn_ViewInfomation_DistrictActionPerformed

    private void btn_ViewInfomation_SupermarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_SupermarketActionPerformed
        btn_ViewInfomation_District.setBackground(color2);
        btn_ViewInfomation_City.setBackground(color2);
        btn_ViewInfomation_Supermarket.setBackground(color1);
        setPanelLayout(jPanelcontent, new Manage_Supermarket());
    }//GEN-LAST:event_btn_ViewInfomation_SupermarketActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        int i = JOptionPane.showConfirmDialog(this, "Are you logout?" ,"" ,JOptionPane.YES_NO_OPTION);
        if(i == JOptionPane.YES_OPTION){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btn_ViewInfomation_CityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_CityMouseEntered
         btn_ViewInfomation_City.setBackground(color3);
         //btn_ViewInfomation_User.setText("<html><font color ='white'>Management User</font></html>");
    }//GEN-LAST:event_btn_ViewInfomation_CityMouseEntered

    private void btn_ViewInfomation_CityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_CityMouseExited
         btn_ViewInfomation_City.setBackground(color2);
          //btn_ViewInfomation_User.setText("<html><font color ='black'>Management User</font></html>");
    }//GEN-LAST:event_btn_ViewInfomation_CityMouseExited

    private void btn_ViewInfomation_DistrictMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_DistrictMouseEntered
         //btn_ViewHistory.setText("<html><font color ='white'>Management History</font></html>");
         btn_ViewInfomation_District.setBackground(color3);
    }//GEN-LAST:event_btn_ViewInfomation_DistrictMouseEntered

    private void btn_ViewInfomation_DistrictMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_DistrictMouseExited
        //btn_ViewHistory.setText("<html><font color ='black'>Management History</font></html>");
        btn_ViewInfomation_District.setBackground(color2);
    }//GEN-LAST:event_btn_ViewInfomation_DistrictMouseExited

    private void btn_ViewInfomation_SupermarketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_SupermarketMouseEntered
        //btn_ViewStatistic.setText("<html><font color ='white'>Management Statistic</font></html>");
        btn_ViewInfomation_Supermarket.setBackground(color3);
    }//GEN-LAST:event_btn_ViewInfomation_SupermarketMouseEntered

    private void btn_ViewInfomation_SupermarketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewInfomation_SupermarketMouseExited
      // btn_ViewStatistic.setText("<html><font color ='black'>Management Statistic</font></html>");
        btn_ViewInfomation_Supermarket.setBackground(color2);
    }//GEN-LAST:event_btn_ViewInfomation_SupermarketMouseExited

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        //setPanelLayout(jPanelcontent, new Home());
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        int i = JOptionPane.showConfirmDialog(this, "Are you want exit ?", "", JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHelpMouseClicked
//       File f1 = new File("test.txt");
//        String pathAbs = "";
//        String[] arrPath = f1.getAbsoluteFile().toString().split("\\\\");
//        for (int i = 0; i < arrPath.length-1; i++) {
//            pathAbs+=arrPath[i]+"\\";
//       }
//        String a = pathAbs.substring(0, pathAbs.length()-1)+"\\src\\UserGuide.doc";
//        callCmdExel.Call(a);
    }//GEN-LAST:event_jLabelHelpMouseClicked

    private void jLabelUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserNameMouseClicked
        //new UpdateInfo(id).setVisible(true);
    }//GEN-LAST:event_jLabelUserNameMouseClicked
    void View_Infomation(){

    }  
    public static  void setPanelLayout(JPanel jpanelSet,JPanel jpanelGet){
      CardLayout cardLayout = (CardLayout)jpanelSet.getLayout();
        jpanelSet.removeAll();
        jpanelSet.add(jpanelGet, "card2");
        cardLayout.next(jpanelSet);
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ViewInfomation_City;
    private javax.swing.JButton btn_ViewInfomation_District;
    private javax.swing.JButton btn_ViewInfomation_Supermarket;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelHelp;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Content;
    private javax.swing.JPanel jPanel_Left;
    private javax.swing.JPanel jPanelcontent;
    // End of variables declaration//GEN-END:variables

}
