/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Infomation_User.java
 *
 * Created on Jan 1, 2011, 7:53:00 PM
 */
package GUI;

import Util.CheckTable;
import bean.District;
import bean.Supermarket;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import service.DistrictService;
import service.SupermarketService;

/**
 *
 * @author ThangAPT
 */
public class Manage_Supermarket extends javax.swing.JPanel {

    SupermarketService supermarketService = new SupermarketService();
    ArrayList<Supermarket> listSupermarkets = null;
    int checkBox = 5;

    public Manage_Supermarket() {
        initComponents();
        initDataTable();
        CheckTable.UnCheckboxTable(jTableUser, checkBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAddNew = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btn_ViewInfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSupermarketName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(572, 493));

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUser);

        jPanel2.setPreferredSize(new java.awt.Dimension(533, 50));

        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/add2.png"))); // NOI18N
        btnAddNew.setText("Add ");
        btnAddNew.setToolTipText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/delete2.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.setToolTipText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btn_ViewInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/note_edit.png"))); // NOI18N
        btn_ViewInfo.setText("Update");
        btn_ViewInfo.setToolTipText("View infomation");
        btn_ViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewInfoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/application_ok.png"))); // NOI18N
        jButton1.setText("Check All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/application_enterprise_delete.png"))); // NOI18N
        jButton2.setText("UnCheck");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ViewInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btn_ViewInfo)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(btndelete))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Supermarket Name:");

        txtSupermarketName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupermarketNameKeyReleased(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/PCI-card_view.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSupermarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSupermarketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel4.setText("Supermarket Manage");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   public void initDataTable() {
        try {
            listSupermarkets = supermarketService.getSupermarkets();
            showDataToTableAndCheckbox(listSupermarkets, jTableUser);
            CheckTable.UnCheckboxTable(jTableUser, checkBox);
        } catch (Exception ex) {
            Logger.getLogger(Manage_Supermarket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        new AddNewSupermarket(this);

    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        Vector v = null;
        v = CheckTable.getValueTable(jTableUser, checkBox);

        if (v.size() == 0) {
            JOptionPane.showMessageDialog(this, "You must select at least one.");
            return;
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure delete ?", "", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                String[] del_ID = null;
                String abc = "";
                for (int i = 0; i < v.size(); i++) {
                    abc += String.valueOf(jTableUser.getValueAt(Integer.parseInt(v.get(i).toString()), 0) + ",");
                }
                del_ID = abc.substring(0, abc.length() - 1).split(",");
                int del = 0;
                try {
                    for (int i = 0; i < del_ID.length; i++) {
                        del = supermarketService.deleteSupermarket(Integer.parseInt(del_ID[i]));
                    }
                    if (del > 0) {
                        JOptionPane.showMessageDialog(this, "Delete succsefull.");
                        initDataTable();
                    }else {
                        JOptionPane.showMessageDialog(this, "Cannot Delete.");
                        return;
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Manage_Supermarket.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                return;
            }
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CheckTable.UnCheckboxTable(jTableUser, checkBox);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CheckTable.CheckboxTable(jTableUser, checkBox);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewInfoActionPerformed
        Vector v = null;
        v = CheckTable.getValueTable(jTableUser, checkBox);
        if (v.size() != 1) {
            JOptionPane.showMessageDialog(this, "You may only choose 1.");
            return;
        } else {
            String id = "";
            id = String.valueOf(jTableUser.getValueAt(Integer.parseInt(v.get(0).toString()), 0));
            new ViewInfoSupermarket(id, this);
            System.out.println("So duoc chon : "+id);
        }
    }//GEN-LAST:event_btn_ViewInfoActionPerformed

    private void txtSupermarketNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupermarketNameKeyReleased
        if(txtSupermarketName.getText().trim().equalsIgnoreCase("")){
            String districtName = txtSupermarketName.getText().trim();
            listSupermarkets = supermarketService.getSupermarketByName(districtName);
            showDataToTableAndCheckbox(listSupermarkets, jTableUser);
            CheckTable.UnCheckboxTable(jTableUser, checkBox);
        }
    }//GEN-LAST:event_txtSupermarketNameKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtSupermarketName.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Name is empty.");
        } else {
            listSupermarkets = supermarketService.getSupermarketByName(txtSupermarketName.getText().trim());
            showDataToTableAndCheckbox(listSupermarkets, jTableUser);
            CheckTable.UnCheckboxTable(jTableUser, checkBox);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void showDataToTableAndCheckbox(ArrayList<Supermarket> list, JTable tbl) {
        Vector vCol = new Vector();
        Vector vRow = new Vector();
        vCol.add("id");
        vCol.add("District");
        vCol.add("Name");
        vCol.add("Address");
        vCol.add("Phone Number");
        vCol.add("");
        ArrayList<District> listDistricts = new DistrictService().getDistricts();
        for (int i = 0; i < list.size(); i++) {
            Vector temp = new Vector();
            String districtName = "";
            temp.add(list.get(i).getId());
            for(int j=0;j<listDistricts.size();j++){
                if(listDistricts.get(j).getDistrictId() == list.get(i).getDistrictId())
                    districtName = listDistricts.get(j).getDistrictName();
            }
            temp.add(districtName);
            temp.add(list.get(i).getName());
            temp.add(list.get(i).getAddress());
            temp.add(list.get(i).getPhone());
            vRow.add(temp);
        }

        tbl.setModel(new DefaultTableModel(vRow, vCol));
        TableColumn cbacc = tbl.getColumnModel().getColumn(checkBox);
        cbacc.setCellEditor(tbl.getDefaultEditor(Boolean.class));
        cbacc.setCellRenderer(tbl.getDefaultRenderer(Boolean.class));
        cbacc.setMaxWidth(30);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btn_ViewInfo;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField txtSupermarketName;
    // End of variables declaration//GEN-END:variables
}
